max_concurrency = 10
insecure = false
user_agent = "lychee/resume-checker"
timeout = 20
max_retries = 3
method = "get"
accept = [200, 201, 204, 206, 300, 301, 302, 303, 304, 307, 308]

exclude = [
    "http://localhost.*",
    "http://127.0.0.1.*",
    "http://0.0.0.0.*",
    "http://10..*",
    "http://172..*",
    "http://192.168..*",
    "file://.*",
    "mailto:.*",
    "^[^/]*\\.md$",
    "^[^/]*\\.png$",
    "^[^/]*\\.jpg$",
    "^[^/]*\\.gif$"
]
