name: Export PDF

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Generate PDF using md-to-pdf
      - name: Convert Markdown to PDF
        run: |
            npm install -g md-to-pdf
            export PUPPETEER_ARGS="--no-sandbox"
            md-to-pdf src/RESUME.md --stylesheet src/PDF.css
            mv src/RESUME.pdf RESUME.pdf

      # Upload PDF as an artifact
      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: RESUME-pdf
          path: RESUME.pdf