name: Export PDF

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update README
        uses: abhinav/stitchmd-action@v1
        with:
            mode: write
            summary: src/RESUME.md
            output: RESUME.md

      # Install Pandoc and LaTeX (required for PDF generation)
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-latex-base texlive-latex-recommended texlive-fonts-recommended texlive-fonts-extra

      # Convert Markdown to PDF using Pandoc
      - name: Convert Markdown to PDF
        run: |
          pandoc RESUME.md -o RESUME.pdf --css=src/PDF.css

      # Upload PDF as an artifact
      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: RESUME-pdf
          path: RESUME.pdf
