name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Generate PDF using md-to-pdf
      - name: Convert Markdown to PDF
        run: |
          npm install -g md-to-pdf
          md-to-pdf src/resume.md --stylesheet src/resume.css --pdf-file resume.pdf

      # Upload PDF as an artifact
      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: resume-pdf
          path: resume.pdf